### PR TITLE
Support custom js marker constructor

### PR DESCRIPTION
**Pull request by Nickztar**
Today we have to use reflection to be able to construct a MarkerWithLabel. Here is a example of what we do:
image

This adds a new method on marker allowing the user specify what js constructor to use. If it's off intrest I could add a example for it later.

Note: I'm not completely sure that calling it jsConstructor is the best but I feel like it fits for what it does in my case atleast.

### CODE REVIEW

**Comment by Nickztar** [comment]
Should probably be added for other methods that do the same thing. Like MarkerList.
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/Maps/Extension/MarkerList.cs#L35

**Comment by valentasm1** [comment]
It looks like MarkerWithLabels is not part of google maps. It is additional package.
Also why you just dont want to extend : ListableEntityBase<MarkerOptions> and create you own class for MarkerWithLabels . Aslo letting pass anything in for constructor isnt good idea.

**Comment by valentasm1** [comment]
So then it is better to create seperate class.

**Comment by Nickztar** [comment]
Yes you are probably correct on that. Will try to change this PR later today or this weekend.

**Comment by valentasm1** [comment]
Thank you very much for understanding.

**Pull request closed without merging**
