### PR TITLE
doc(README): remove typo

### PR DESCRIPTION
**Pull request by Deep145757**
## Description:

This Pull Request fixes a typographical error in the README.md file.

## Changes Made:

 - Corrected "forgor" to "forgot" in the README.md file.
 - Corrected "componenent" to "component" in the README.md file.

## Additional Information:

This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.

Thank you for considering this contribution.

### CODE REVIEW

**Comment by valentasm1** [comment]
I edited by myself. Thank you for noticing it.

**Comment by valentasm1** [comment]
You look like robot. I dont like robots.

**Comment by Deep145757** [comment]
definitely not a ROBO

**Comment by valentasm1** [comment]
Thats what robot would say. Just forget and move on.

**Comment by Deep145757** [comment]
😑

**Pull request closed without merging**
