### PR TITLE
Advanced component rendered with Blazor

### PR DESCRIPTION
**Pull request by Nickztar**
Somewhat of a WIP/MVP but it is working really well and feels very nice to work with. Went a bit outside the current code to support this so didn't use some of the features that are built in. But feels free to try the example page and see how you feel. Am open to suggestions on changing the API. This is how I plan on using it so made it work

### CODE REVIEW

**Comment by valentasm1** [comment]
At first i thought you about gmp-map, but since you reuse google maps it isnt.
https://developers.google.com/maps/documentation/javascript/add-google-map-wc-tut

What is motivation?
Where was issue and how your changes solved something?

It is Halloween/holiday season so at the best case i could release only next week. I want to play around and maybe find some bugs :). Overall all looks great.

**Comment by Nickztar** [comment]
Yea was thinking about gmp-map but really like working with most of the code in C#.

Motivation was looking into replacing our normal markers (with label) with advanced markers. But I would like to avoid doing js invoke everytime we render. We do a lot of realtime updates so it adds up to a lot of latency/performance. This way I avoid calling js when just rendering default and allows me to render things normally in blazor.

Absolutely no rush, I set it as draft to just make not that I'm working on it. Probably has some tweaks/bugs to figure out so will be testing and changing some things. 

Have a nice holiday 👍🏻

**Comment by Nickztar** [comment]
Feels like the API is good now. Has the ability to do most things, will try it in my own application later today and then I think it will be ready for review unless something goes horribly wrong 😄

**Comment by Nickztar** [comment]
Changed my mind on some things after testing it out in my application. Doesn't feel as smooth as expected when working with clustering. Will change some stuff to try and make it more usable. 😄

**Comment by Nickztar** [comment]
@valentasm1 It currently feels like it's at a good starting point. Definitly might be some things that people would like in the future but we can add that when it appears. Feel free to check it out and try to break it!

Changed to make sure it works with non-beta version of google maps. Since that feels a bit limiting. Currently using it in my app where we render markers with realtime data and somewhat complex markers, working really well, even with clustering 🚀

**Comment by valentasm1** [comment]
Looks great thank you very much for your time.
https://www.nuget.org/packages/BlazorGoogleMaps/4.9.0

**Pull request merged**
