### PR TITLE
Add drawingManager suppressUndo undocumented parameter.

### PR DESCRIPTION
**Pull request by markschroeder77**
This PS allows one to hide the undo button in the drawing manager by adding the undocumented suppressUndo parameter to the PolygonOptions class.

### CODE REVIEW

**Comment by valentasm1** [comment]
I dont get it. I tried to drawing manager, but i dont see any undo.
 Small demo to reporduce?

**Comment by markschroeder77** [comment]
undo
[Map2.zip](https://github.com/rungwiroon/BlazorGoogleMaps/files/11994635/Map2.zip)

Sorry it actually has nothing to do with DrawingManager, it's a Polyline option. (I was just using it with DrawingManager at the time)
It allows one to hide the undo button that comes up when a polyline is user edited.
I think it may only work with the beta version of Google Maps.

To demo:

- navigate to the /mapPolyline page
- click "start drawing polyline"
- finish drawing a polyline
- now edit the polyline by dragging on of the dots

**Comment by valentasm1** [comment]
Now it make sense. Screenshot helped a lot.

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/3.0.8

**Pull request merged**
