### PR TITLE
Implementation of Autocomplete

### PR DESCRIPTION
**Pull request by willapp**
Implemented the Autocomplete behaviour based on the documented API surface [here](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/reference/places-widget#Autocomplete).

Created a new example page in the server-side demo app, based loosely on the example [here](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/places-autocomplete).

Also tidied up a few bits of dead code/references.

### CODE REVIEW

**Comment by valentasm1** [comment]
Thumb up for clear comments

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/0.5.4
Again thank you for contribution. I wanted to test out autocomplete, but looks we reached limits for key. Will try other day.

**Comment by valentasm1** [comment]
Tested bounds. Looks working

**Comment by willapp** [comment]
Thanks for the merge + nuget update. Next PR I will amend the documentation to highlight that using Autocomplete requires the Google JS library script URL to have **&libraries=places** appended, otherwise none of the _google.maps.places_ namespaced types are loaded.

**Pull request merged**
