### PR TITLE
Implement AutocompleteService, Geocoder and PlacesService

### PR DESCRIPTION
**Pull request by Curlack**
Complete implementation of Google's AutocompleteService and Geocoder. Partial implementation of Google's PlacesService.

### CODE REVIEW

**Comment by valentasm1** [comment]
1. This is massive. I think you could merge if conditions in js file. 
2. Also not sure but looks like you mixing  System.Text.Json.Serialization and Newtonsoft. Maybe it was before alread. I dont know.
3. Also i am not sure about default! operator. It looks just as a way to avoid compiler errors.
4. Need couple demos. Preferably in server side
I think 1,4 should be fixed and 2,3 just my thoughts. Since you did all stuff so i am sure these things have reason to be there.

Could you give official links these features?
I will play around with demos and then merge.

**Comment by Curlack** [comment]
Hi,
Thanks for the review. Great work with this library by the way. I especially love what you guys did with the `JsObjRef `class. Very clever.

1. I wasn't sure if you would approve merging the if conditions, since I'm checking different instances. Especially with the PlacesService, where the logic applied will be different for NearbySearch and TextSearch methods. I didn't have enough time to see how to handle the PlaceSearchPagination object coming from javascript, so I skipped these. I also chose to check instanceof instead of individual method names e.g. `getPlacePredictions `and `getQueryPredictions `in the `AutocompleteService`.
2. Regarding the mixing of `System.Text.Json` and `Newtonsoft.Json`, according to my research, Blazor doesn't support customization of how objects are serialized into C#, coming from javascript. So for this reason I used `System.Text.Json` for any results/responses (coming from javascript), where the property name contains an underscore. I'm also a `Newtonsoft.Json` fan, so would've gone the extra mile to stick to it, if I could find some documentation or code samples.
3. The default! operator is to reduce warnings. I try to keep the gutter clean :), but it also makes me think sometimes. I use this operator whenever the google docs doesn't indicate that the parameter is optional. For all optional parameters I used the question mark (?) e.g. `string?`
4. I will quickly create you some demos shortly.

Our previous javascript project used the Autocomplete directly i.e. Google would wire the dropdown list to an existing input text control and I'm beginning to think I should do the same in our new Blazor project (port from old js project). However, we looking to integrate with `Syncfusion.Blazor` controls, in which case I already have an `AutoComplete` control. Syncfusion's suggestion is to utilize the `AutocompleteService` and manage the filter list manually, including the `AutocompleteSessionToken` and `PlacesService.GetDetail`.
We use google services for the map and address input controls. Since you've already covered all we need regarding the map. I was hoping you'd be open to implementing the rest of the services. That way I don't need to add a bunch of nuget packages. One is enough ;).

PlacesService: https://developers.google.com/maps/documentation/javascript/reference/places-service
AutocompleteService: https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service
Geocoder: https://developers.google.com/maps/documentation/javascript/reference/geocoder

**Comment by valentasm1** [comment]
I am not sure who gonna support these features. I wont list all exiting libraries which are polished, but there are some.  If it would be mine project, then for sure i wont add these features, but i know it was requested couple times some time ago.  Maybe we could work it out and lets add them

**Comment by Curlack** [comment]
I've added the demo page and found a couple of bugs. One of them was deserialization of the enums. Turns out System.Text.Json needed the converter on the property. Might be due to conflicts in the usings. Anyway, it's now working at least. the enums are now Newtonsoft.Json again so minimum usage of System.Text.Json i.e. services responses only.

Looking forward to hearing your thoughts.
Thanks

**Comment by Curlack** [comment]
Almost forgot. There's a change in `objectManager.js` that I'm not sure is required, but I'm unable to figure out why the `sessionToken` `JsObjRef `doesn't contain the `guidString `property during the `PlacesService.GetDetails` call, but it's there during the `AutocompleteService.GetPlacePredictions`. Was wondering if might have an idea.

**Comment by valentasm1** [comment]
I future i want to get rid of Newtonsoft. 
You dont need additional serializers.
In asp core you just need to set for model binder enum to string serializer and it works
```
services
            .AddControllers()
            .AddJsonOptions(opts =>
            {
                opts.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
            });
```
In this case not sure why it dont work but setting on property explicitly looks working (at least for me). Please do so and then we could merge. 
I dont know about guidString issue. 
```
public class AutocompleteResponse
    {
        public AutocompletePrediction[] Predictions { get; set; } = new AutocompletePrediction[] { };

        [JsonConverter(typeof(JsonStringEnumConverter))]
        public PlaceServiceStatus Status { get; set; }
    }
```

**Comment by Curlack** [comment]
The converter is required to handle the custom naming e.g., `RequestDenied` vs `request_denied`. Apparently, it is not supported. See this [stackoverflow](https://stackoverflow.com/a/72643851/1766275) answer for the detail. If the `GeocoderStatus` comes back as `RequestDenied`, the built-in `JsonStringEnumConverter` will throw a `JsonException`: "The JSON value could not be converted...".

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

var options = new JsonSerializerOptions();
options.Converters.Add(new JsonStringEnumConverter());

var status = JsonSerializer.Deserialize<GeocoderStatus>("\"REQUESTDENIED\"", options); // This works,
status = JsonSerializer.Deserialize<GeocoderStatus>("\"REQUEST_DENIED\"", options); //...but this doesn't (underscore)
```

Since you eventually want to move away from Newtonsoft, there is a library called [Macross.Json.Extensions](https://www.nuget.org/packages/Macross.Json.Extensions/) _(76.44 KB)_, that takes care of `System.Text.Json`'s short comings, this issue included.

Perhaps, for now, we use the additional converter until we move over to `System.Text.Json`?

**Comment by valentasm1** [comment]
I am saying in migrate in future. Since everything works by now no rush. 
Then converter makes sense.
Thank you for stackoverflow link. I will subscribe for that runtime ticket and after it will be sovled then i will give a shot for migration.

**Comment by valentasm1** [comment]
I will release nuget tomorrow (after ~10h).

**Comment by Curlack** [comment]
Excellent! Thank you. Much appreciated.

**Comment by Curlack** [comment]
I'm quickly having a look to see if I can figure out why the `guidString` property is missing from the `AutocompleteSessionToken`

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.1
Thank you very much for your work.

**Pull request merged**
