### PR TITLE
Return OverviewPolyline in DirectionsRoute object

### PR DESCRIPTION
**Pull request by NickBarrett**
Hi there,

This code enables the return of the OverviewPolyline property in a DirectionsRoute of a DirectionsResult.

Not sure why it was purposefully being removed from the object returned from js.

Without this modification, the AddDirections method in MapRoutes demo page would not return any value to the OverviewPolyline property of the routes in the _directionsResult.

### CODE REVIEW

**Comment by valentasm1** [comment]
@cyberyaga could check? I also dont understand why he removed r.overview_polyline from DirectionResult. Based on comment it is because it is heavy collection. Soo does it mean you get some exception on serialization sometimes. Or does it slow down map a lot? @NickBarrett why you think it was removed? Bug?

**Comment by NickBarrett** [comment]
We tried bypassing cleanDirectionResult in order to get the full result.
When testing in ClientSideDemo it worked fine but in ServerSideDemo it initially would not return anything
We had to make the following changes to `Startup.ConfigureServices`
```services.AddServerSideBlazor().AddHubOptions(config => config.MaximumReceiveMessageSize = 1048576);```
It appears that the default message size limits of SignalR (32K) is not large enough to pass the results from javascript back to the .net code.

I can see that because of this, some may want to reduce the returning payload as much as possible in order to reduce the chance of seemingly random failures. That said, from our testing, returning `overview_path` hasn't caused a problem. `steps` though, is definitely a problem (when running server side blazor).

**Comment by valentasm1** [comment]
Great observations. I will try to merge today latter and will add optional params to includes these extra properties in route result. By default they wont be included. 
Also will update readme with MaximumReceiveMessageSize information too. You could MaximumReceiveMessageSize to unlimited (=null) and hope nothing will break.

**Comment by valentasm1** [comment]
Added several changes regarding your issue.

By default all paths are still striped (yea, i reverted your changes), but know you could opt out default behaviour by passing options.
I have bad feeling that i made mistake somewhere so please check and let me know if it is ok.
```
_directionsResult = await dirRend.Route(dr, new DirectionsRequestOptions()
{
	StripLegsStepsLatLngs = false,
	StripOverviewPath = false,
	StripOverviewPolyline = false,
	StripLegsStepsPath = false,
	StripLegsSteps = false
});
```

New Nuget
https://www.nuget.org/packages/BlazorGoogleMaps/0.6.7


Js code just for curiousity
```
//Strips the DirectionResult from some of the heaviest collections.
//ServerSide (Client Side have no issues) reach MaximumReceiveMessageSize (32kb) and crash if we return all data
//Workaround is to increase limit MaximumReceiveMessageSize
function cleanDirectionResult(dirResponse, dirRequestOptions) {
    let tmpdirobj = JSON.parse(JSON.stringify(dirResponse));

    tmpdirobj.routes.forEach((r) => {
        if (dirRequestOptions == undefined || dirRequestOptions.stripOverviewPath) {
            r.overview_path = [];
        }

        if (dirRequestOptions == undefined || dirRequestOptions.stripOverviewPolyline) {
            r.overview_polyline = '';//Previously was []. Why??? it is a string
        }

        r.legs.forEach((l) => {
            if (dirRequestOptions == undefined || dirRequestOptions.stripLegsSteps) {
                l.steps = [];
            } else {
                l.steps.forEach((step) => {
                    if (dirRequestOptions == undefined || dirRequestOptions.stripLegsStepsLatLngs) {
                        step.lat_lngs = [];
                    }

                    if (dirRequestOptions == undefined || dirRequestOptions.stripLegsStepsPath) {
                        step.path = [];
                    }
                });
            }
        });
    });

    return tmpdirobj;
}
```

**Pull request merged**
