### PR TITLE
Resolve javascript namespace issue, argument null exception and setDirections unsupported.

### PR DESCRIPTION
**Pull request by Curlack**
This resolves https://github.com/rungwiroon/BlazorGoogleMaps/issues/223, resolves https://github.com/rungwiroon/BlazorGoogleMaps/issues/224, resolves https://github.com/rungwiroon/BlazorGoogleMaps/issues/225.

Also cleaned up the MapRoutes demo code to be able to Add and Remove routes as many times as you need.

### CODE REVIEW

**Comment by valentasm1** [comment]
Citation from related issue
The changes to objectManager.js looks vicious, in short, I only move the entire script into blazorGoogleMaps object that is returned by IIFE (immediately invoked function expression). I did this so we can encapsulate private members. Then I moved the directionService handler (previously known as googleMapDirectionServiceFunctions.route) into its own object (for neatness's sake, wasn't really required). Hopefully doesn't cause too much headache with the conflicts. If it wasn't changed between last time and now, maybe just replacing would be easier.
Anyway, hope this helps.

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.3
Please update your fork to latest version

**Comment by valentasm1** [comment]
Maybe you done hosting webassebly on github pages?
I did but long time ago and dont remember exactly. Would be great to host demos.

**Comment by Curlack** [comment]
I haven't, but yes would be nice. Will look into it sometime and let you
know.

**Comment by valentasm1** [comment]
Thank you very much for support :).

**Comment by valentasm1** [comment]
I did hosted on github pages. Finally.
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/.github/workflows/main.yml
Keypoint was to enable github pages in settings
https://github.com/rungwiroon/BlazorGoogleMaps/issues/228

**Comment by valentasm1** [comment]
https://rungwiroon.github.io/BlazorGoogleMaps/mapInfoWindow

**Comment by Curlack** [comment]
Nice! Sorry haven't had the time to experiment with it a bit. Will have a
look, thanks and well done.

**Comment by valentasm1** [comment]
I support anything as soon as someone does for me :). This sounds like could take some time to implement.

**Comment by Curlack** [comment]
No problem. Hahaha. I already have a working concept. Just need to
'Blazorize' it :) Was thinking Directions and child Route components should
do the trick. When I have some time will send you a PR. Thanks.

**Comment by Curlack** [comment]
Good morning. I was wondering if there's a way we can communicate other than posting messages back and forth via an issue (unless that is how it's suppose to be). I've been working on the rendering of multiple routes, but can't quite find a way to implement, that is to my liking yet. Want to pick your brain a bit if you don't mind.
Please let me know if we should continue communicating as we've been doing or if there's another way you prefer.
Thanks

**Comment by valentasm1** [comment]
You could create issue and we could have endless discussion there. Sometimes it help to have public history that other could see and maybe find answer.

**Pull request merged**
