### PR TITLE
Extensions to the listable entities:

### PR DESCRIPTION
**Pull request by Franz1960**
- New PolylineList class.
- New method SetMultipleAsync() to combine remove, add and modify operations on lists.
- New static methods ManageAsync() to manage lifetime of lists.

### CODE REVIEW

**Comment by Franz1960** [comment]
Sorry to trouble you with pull requests. These extensions make your lib really good for my app. Should I insert a demo page?
I'm using the project output, no urgent need for nuget packages for me.
Cheers, Franz

**Comment by valentasm1** [comment]
I will review tomorow or day after tomorw. Xmas so worst case this week.

**Comment by Franz1960** [comment]
Click event handler added to all ListableEntityBase derived classes. The click event provides MouseEvent data plus entity key and value.

**Comment by valentasm1** [comment]
One more thing to note. I am a bit suspicious that you made changes in core helpers. Since rest changes looks professional and clearly documented so you get my trust. I assume you know what you are doing.
Maybe need to change naming of method name Manage. It is not so obvious. In other hand i couldnt think something else. If you come with other name let me know. We could change it while it is not so much used.

**Comment by Franz1960** [comment]
Maybe "KeepSynced" would be better than "Manage"? It keeps the entities in ListableEntityListBase (and the google map component) synchronized to the entities in the app. Should I change and commit to the branch?

**Comment by valentasm1** [comment]
Agree. Sync sounds more like it what function does. I left only sync. Released nuget 1.0.1 and pushed changes.
Btw thank you for such huge changes.

**Pull request merged**
