### PR TITLE
Adding events listeners to ListableEntityListBase

### LINKED ISSUE #76: Adding events for ListableEntityListBase
This is a follow up to #59.
Now that CircleList is implemented, consider the following scenario:
1. A list of many circles are added to the map (tens of thousands in my case ).
2. A click event is attached to each of the circles (of which typically only few will actually be clicked).

Since #64 item 1 is fast, but attaching the events is still done per item - which is very slow.
I'm thinking of something of the sort of:
```C#
            CircleList circles = await CircleList.CreateAsync(JsRuntime, options);
            Action<Circle> clickAction = (circleInstance) =>
            {
                //The circleInstance was Clicked!
            };

            await circles.AddListener("click", clickAction);
```
Where the instance is passed as an argument to the raised event.

Instead of the current:

```C#
            CircleList circles = await CircleList.CreateAsync(JsRuntime, options);
            foreach (KeyValuePair<string, Circle> pair in circles.BaseListableEntities)
            {
                Circle circle = pair.Value;
                Action clickAction = () =>
                {
                    //I got Clicked!
                };

                await circle.AddListener("click", clickAction);
            }
```

@rungwiroon , If I'll find the time I'll implement & open a PR.  
Is there anything I should be aware of?
Any tips?

### PR DESCRIPTION
**Pull request by turner11**
Currently the callback returns a json the contains info about lon/lat of the click (as per [[1]](https://developers.google.com/maps/documentation/javascript/reference#Circle), click event).
So far I was not able to figure out how to get the GUID of an item using the event.
The event's parameter is a MouseEvent isntance, which gets a GUID, but it seems its the click's GUID rather than the clicked-item's GUID.

closes #76

### CODE REVIEW

**Comment by turner11** [comment]
Added also a Page for easier visualization.
For testing:
1. Go to the `Batch of Circles` Page.
2. Click on `Add Circles` Button.
3. Click on a Circle

**Comment by valentasm1** [comment]
This pull request is still a work in progress. What does it mean?
Code looks a bit advanced at some parts, but if it work then no complain.

**Comment by turner11** [comment]
It means that it does not work yet...
As described, I am not able to get the clicked item using the event.
Any suggestions?
I am not fluent in JavaScript, so if there is something there I'm doing wrong - I'll be happy to learn :)

**Comment by valentasm1** [comment]
I think it is impossible. I am way worse in js than you :).
You could try keep reference of item in closure like here guy did with position
https://github.com/rungwiroon/BlazorGoogleMaps/issues/62

**Comment by Franz1960** [comment]
Hi, I implemented a click event handler using a closure. That means an event handler is added to every entity and the callback in C# uses the entity key and value to propagate the event to the application. It's working for me with several thousands of circles on the map without significant performance flaw. See my pull request #82. Cheers, Franz

**Comment by valentasm1** [comment]
@turner11 does #82 and latest nuget 1.0.1 fulfil you requiraments?
IMO it does exaclty what you wanted. Should i close/remove PR?

**Comment by turner11** [comment]
@valentasm1 , go ahead and close it. I won't have time to check it in the up coming week.  
If the issue still still relevant, I'll reopen when I get to it.

**Pull request closed without merging**
